openapi: 3.0.4
info:
  title: Airports Lookup
  description: Airports is a simple tool for getting airport data. It returns the airport name, location, and more.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/airports:
    get:
      summary: Get Airport Info from IATA
      description: Airports is a simple tool for getting airport data. It returns the airport name, location, and more.
      operationId: airports
      parameters:
      - name: iata
        in: query
        schema:
          type: string
        required: true
        description: The IATA code of the airport for which you want to get the information (e.g., MCI)
        example: MCI
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  icao: KMCI
                  iata: MCI
                  name: Kansas City International Airport
                  city: Kansas City
                  state: Missouri
                  country: US
                  elevation: 1026
                  lat: 39.2975997925
                  lon: -94.7138977051
                  tz: America/Chicago
                  city_info:
                    name: Kansas City
                    altName: ''
                    country: US
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
